"""
Generate jur_abkuerzungen_final.csv from openjur.de data.
Since the page is JS-rendered, we hardcode the scraped data.
"""
import csv
import os

OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "jur_abkuerzungen_final.csv")

# All abbreviations from openjur.de/s/abkuerzungen.html
# Format: (Bedeutung, Abkürzung)
# Plus essential Gesetzes-Abkürzungen for the E-Examen
ENTRIES = [
    # ── openjur.de Praxis-Abkürzungen ──
    ("am angegebenen Ort", "a.a.O."),
    ("Absatz", "Abs."),
    ("Amtsgericht", "AG"),
    ("Aktiengesellschaft", "AG"),
    ("Allgemeine Geschäftsbedingungen", "AGB"),
    ("Artikel", "Art."),
    ("Auflage", "Aufl."),
    ("abgedruckt", "abgedr."),
    ("abweichend", "abw."),
    ("am Ende", "a.E."),
    ("ablehnend", "abl."),
    ("alte Fassung", "a.F."),
    ("anderer Ansicht", "a.A."),
    ("Amtsblatt", "ABl."),
    ("actio libera in causa", "a.l.i.c."),
    ("Alternative", "Alt."),
    ("Anhang", "Anh."),
    ("Anmerkung", "Anm."),
    ("argumentum", "arg."),
    ("ausdrücklich", "ausdr."),
    ("Artikel (Mehrzahl)", "Artt."),
    ("Gegenschluss", "arg. e contr."),
    ("allgemein", "allg."),
    ("allgemeine Meinung", "allg.M."),
    ("Anlage", "Anl."),
    ("ausführlich", "ausf."),
    ("Aktenzeichen", "Az."),
    ("ausschließlich", "ausschl."),
    ("Arbeitsgericht", "ArbG"),
    ("beglaubigt", "begl."),
    ("begründet", "begr."),
    ("betreffend", "betr."),
    ("bestritten", "bestr."),
    ("Bestimmung", "Best."),
    ("Berufung", "Bfg."),
    ("Berufungsgericht", "BfgGer."),
    ("Band", "Bd."),
    ("Blatt", "Bl."),
    ("beziehungsweise", "bzw."),
    ("Beilage", "Beil."),
    ("Beschluss", "Beschl."),
    ("Besprechung", "Bespr."),
    ("Begründung", "Bgr."),
    ("Beispiel", "Bsp."),
    ("beispielsweise", "bspw."),
    ("bezüglich", "bzgl."),
    ("Bundesgerichtshof", "BGH"),
    ("Bundesverfassungsgericht", "BVerfG"),
    ("Bundesverwaltungsgericht", "BVerwG"),
    ("Bundessozialgericht", "BSG"),
    ("Bundesarbeitsgericht", "BAG"),
    ("Bundesfinanzhof", "BFH"),
    ("Bundespatentgericht", "BPatG"),
    ("Bayerisches Oberstes Landesgericht", "BayObLG"),
    ("culpa in contrahendo", "c.i.c."),
    ("dagegen", "dagg."),
    ("derselbe", "ders."),
    ("das heißt", "d.h."),
    ("dergleichen", "dgl."),
    ("Drucksache", "Drs."),
    ("ebenso", "ebso."),
    ("eingeführt", "eingef."),
    ("entgegen", "entgg."),
    ("entsprechend", "entspr."),
    ("Erklärung", "Erkl."),
    ("Erlass", "Erl."),
    ("eventuell", "evtl."),
    ("ergänzend", "erg."),
    ("Ergebnis", "Erg."),
    ("Erwägungsgrund", "Erw.Gr."),
    ("Europäisches Parlament", "EP"),
    ("Europäischer Rat", "ER"),
    ("folgende (Seiten)", "ff."),
    ("früher", "fr."),
    ("folgende (Seite)", "f."),
    ("Finanzgericht", "FG"),
    ("gemäß", "gem."),
    ("gegebenenfalls", "ggf."),
    ("gegenüber", "ggü."),
    ("Grund", "Grd."),
    ("Großer Senat", "Gr.S."),
    ("Gemeinsamer Senat der obersten Gerichtshöfe des Bundes", "GmS-OGB"),
    ("herrschende Meinung", "h.M."),
    ("Handlung", "Hdlg."),
    ("Halbsatz", "Hs."),
    ("Herausgeber", "Hrsg."),
    ("herrschende Ansicht", "h.A."),
    ("im Sinne von", "i.S.v."),
    ("im engeren Sinne", "i.e.S."),
    ("im Grundsatz", "i.Grds."),
    ("im gleichen Sinn", "i.gl.S."),
    ("im Ergebnis", "i.Erg."),
    ("in der Fassung", "i.d.F."),
    ("im Rahmen des", "i.R.d."),
    ("im Rahmen von", "i.R.v."),
    ("in Verbindung mit", "i.V.m."),
    ("im Wesentlichen", "i.W."),
    ("im weiteren Sinne", "i.w.S."),
    ("in der Regel", "i.d.R."),
    ("im Übrigen", "i.Ü."),
    ("im Einzelnen", "i.E."),
    ("juristisch", "jur."),
    ("kritisch", "krit."),
    ("Kammergericht", "KG"),
    ("laut", "lt."),
    ("laufend", "lfd."),
    ("Leitsatz", "LS"),
    ("Landessozialgericht", "LSG"),
    ("Landesverfassungsgericht", "LVerfG"),
    ("littera", "lit."),
    ("mit Besprechung", "m. Bespr."),
    ("mit Anmerkung", "m. Anm."),
    ("mit weiteren Nachweisen", "m.w.N."),
    ("monatlich", "mtl."),
    ("mündlich", "mdl."),
    ("mit Wirkung vom", "m.W.v."),
    ("neue Fassung", "n.F."),
    ("nicht rechtskräftig", "n.rk."),
    ("nomen nominandum", "n.n."),
    ("ohne Jahresangabe", "o.J."),
    ("ordentlich", "ord."),
    ("Orientierungssatz", "OS"),
    ("Oberlandesgericht", "OLG"),
    ("Oberverwaltungsgericht", "OVG"),
    ("Randnummer", "Rn."),
    ("Rechtsprechung", "Rspr."),
    ("Richter", "Ri."),
    ("Revision", "Rev."),
    ("Randziffer", "Rdz."),
    ("siehe auch", "s.a."),
    ("skeptisch", "skept."),
    ("strittig", "str."),
    ("ständige Rechtsprechung", "st.Rspr."),
    ("Streitverfahren", "Str.Verf."),
    ("siehe", "s."),
    ("siehe dort", "s.d."),
    ("sofortig", "sof."),
    ("sogenannt", "sog."),
    ("Staatsanwaltschaft", "StA"),
    ("stillschweigend", "stillschw."),
    ("Streitwert", "StrWert."),
    ("subjektiv", "subj."),
    ("Sozialgericht", "SG"),
    ("Staatsgerichtshof", "StGH"),
    ("teilweise", "teilw."),
    ("unter anderem", "u.a."),
    ("und ähnliche", "u.ä."),
    ("umstritten", "umstr."),
    ("unbekannt", "unbek."),
    ("unbestimmt", "unbest."),
    ("unpfändbar", "unpfb."),
    ("unzulässig", "unzul."),
    ("unzuständig", "unzustd."),
    ("Urteil", "Urt."),
    ("Urteilsverkündung", "UrtVerk."),
    ("überwiegend", "überw."),
    ("Überblick", "Üb."),
    ("Übereinkommen", "Übk."),
    ("vergleiche", "vgl."),
    ("Variante", "Var."),
    ("vorangehend", "vorangeh."),
    ("Vorbemerkung", "Vorbem."),
    ("vorgenannt", "vorgen."),
    ("von Amts wegen", "v.A.w."),
    ("Verfahren", "Verf."),
    ("Verhandlungen", "Verh."),
    ("Verkündungen", "Verk."),
    ("Veröffentlichungen", "Veröf."),
    ("Verfügung", "Vfg."),
    ("Verwaltungsgericht", "VG"),
    ("Verfassungsgerichtshof", "VerfGH"),
    ("Verwaltungsgerichtshof", "VGH"),
    ("zutreffend", "zutr."),
    ("zweifelhaft", "zw."),
    ("zustimmend", "zust."),
    ("zusammenfassend", "zusf."),

    # ── Wichtige Gesetzes-Abkürzungen (E-Examen) ──
    ("Bürgerliches Gesetzbuch", "BGB"),
    ("Strafgesetzbuch", "StGB"),
    ("Strafprozessordnung", "StPO"),
    ("Zivilprozessordnung", "ZPO"),
    ("Grundgesetz", "GG"),
    ("Handelsgesetzbuch", "HGB"),
    ("Verwaltungsgerichtsordnung", "VwGO"),
    ("Verwaltungsverfahrensgesetz", "VwVfG"),
    ("Verwaltungsvollstreckungsgesetz", "VwVG"),
    ("Gesetz über Ordnungswidrigkeiten", "OWiG"),
    ("Gerichtsverfassungsgesetz", "GVG"),
    ("Insolvenzordnung", "InsO"),
    ("Sozialgerichtsgesetz", "SGG"),
    ("Finanzgerichtsordnung", "FGO"),
    ("Gesetz gegen den unlauteren Wettbewerb", "UWG"),
    ("Gesetz gegen Wettbewerbsbeschränkungen", "GWB"),
    ("Urheberrechtsgesetz", "UrhG"),
    ("Bundesdatenschutzgesetz", "BDSG"),
    ("Datenschutz-Grundverordnung", "DSGVO"),
    ("Aktiengesetz", "AktG"),
    ("GmbH-Gesetz", "GmbHG"),
    ("Gewerbeordnung", "GewO"),
    ("Bundesimmissionsschutzgesetz", "BImSchG"),
    ("Baugesetzbuch", "BauGB"),
    ("Aufenthaltsgesetz", "AufenthG"),
    ("Asylgesetz", "AsylG"),
    ("Jugendgerichtsgesetz", "JGG"),
    ("Betäubungsmittelgesetz", "BtMG"),
    ("Waffengesetz", "WaffG"),
    ("Straßenverkehrsgesetz", "StVG"),
    ("Straßenverkehrsordnung", "StVO"),
    ("Einkommensteuergesetz", "EStG"),
    ("Körperschaftsteuergesetz", "KStG"),
    ("Umsatzsteuergesetz", "UStG"),
    ("Abgabenordnung", "AO"),
    ("Gerichtskostengesetz", "GKG"),
    ("Rechtsanwaltsvergütungsgesetz", "RVG"),
    ("Bundesverfassungsgerichtsgesetz", "BVerfGG"),
    ("Arbeitsgerichtsgesetz", "ArbGG"),
    ("Kündigungsschutzgesetz", "KSchG"),
    ("Betriebsverfassungsgesetz", "BetrVG"),
    ("Teilzeit- und Befristungsgesetz", "TzBfG"),
    ("Mutterschutzgesetz", "MuSchG"),
    ("Bundesurlaubsgesetz", "BUrlG"),
    ("Arbeitszeitgesetz", "ArbZG"),
    ("Allgemeines Gleichbehandlungsgesetz", "AGG"),
    ("Mindestlohngesetz", "MiLoG"),
    ("Sozialgesetzbuch I", "SGB I"),
    ("Sozialgesetzbuch II", "SGB II"),
    ("Sozialgesetzbuch III", "SGB III"),
    ("Sozialgesetzbuch V", "SGB V"),
    ("Sozialgesetzbuch X", "SGB X"),
    ("Bundeswahlgesetz", "BWahlG"),
    ("Polizeiaufgabengesetz", "PAG"),
    ("Versammlungsgesetz", "VersG"),
    ("Bundesnaturschutzgesetz", "BNatSchG"),
    ("Kreislaufwirtschaftsgesetz", "KrWG"),
    ("Wasserhaushaltsgesetz", "WHG"),
    ("Bundesberggesetz", "BBergG"),
    ("Wohnungseigentumsgesetz", "WEG"),
    ("Erbbaurechtsgesetz", "ErbbauRG"),
    ("Sachenrechtsbereinigungsgesetz", "SachenRBerG"),
    ("Beurkundungsgesetz", "BeurkG"),
    ("Rechtsdienstleistungsgesetz", "RDG"),
    ("Bundesnotarordnung", "BNotO"),
    ("Bundesrechtsanwaltsordnung", "BRAO"),
    ("Einführungsgesetz zum BGB", "EGBGB"),
    ("Produkthaftungsgesetz", "ProdHaftG"),
    ("Versicherungsvertragsgesetz", "VVG"),
    ("Personenstandsgesetz", "PStG"),
    ("Grundbuchordnung", "GBO"),
    ("Zwangsvollstreckungsgesetz", "ZVG"),

    # ── Typische Klausur-Floskeln (openjur-Stil) ──
    ("Paragraph", "§"),
    ("Paragraphen", "§§"),
    ("Nummer", "Nr."),
    ("Satz", "S."),
    ("Buchstabe", "lit."),
    ("Seite", "S."),
    ("Randnummer", "Rn."),
    ("und so weiter", "etc."),
    ("das heißt (lateinisch)", "i.e."),
    ("zum Beispiel", "z.B."),
    ("und andere", "et al."),
    ("oben genannte", "o.g."),
    ("Vertragsverletzungsverfahren", "VVV"),
    ("Europäischer Gerichtshof", "EuGH"),
    ("Europäischer Gerichtshof für Menschenrechte", "EGMR"),
    ("Internationaler Gerichtshof", "IGH"),
    ("Internationaler Strafgerichtshof", "IStGH"),
    ("Bundesanzeiger", "BAnz"),
    ("Bundesgesetzblatt", "BGBl."),
    ("Neue Juristische Wochenschrift", "NJW"),
    ("Juristische Schulung", "JuS"),
    ("Juristische Arbeitsblätter", "JA"),
    ("Juristenzeitung", "JZ"),
    ("Neue Zeitschrift für Strafrecht", "NStZ"),
    ("Neue Zeitschrift für Verwaltungsrecht", "NVwZ"),
    ("Neue Zeitschrift für Arbeitsrecht", "NZA"),
    ("Monatsschrift für Deutsches Recht", "MDR"),
    ("Zeitschrift für Zivilprozess", "ZZP"),
    ("Entscheidungen des Bundesgerichtshofes in Zivilsachen", "BGHZ"),
    ("Entscheidungen des Bundesgerichtshofes in Strafsachen", "BGHSt"),
    ("Entscheidungen des Bundesverfassungsgerichts", "BVerfGE"),
    ("Entscheidungen des Bundesverwaltungsgerichts", "BVerwGE"),
]

def deduplicate(entries):
    seen = set()
    result = []
    for desc, abbr in entries:
        key = abbr.strip()
        if key not in seen:
            seen.add(key)
            result.append((desc, abbr))
    return result

def main():
    entries = deduplicate(ENTRIES)
    entries.sort(key=lambda x: x[1].lower())

    with open(OUTPUT, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f, delimiter=";")
        writer.writerow(["Begriff", "Abkürzung"])
        for desc, abbr in entries:
            writer.writerow([desc, abbr])

    print(f"Geschrieben: {OUTPUT}")
    print(f"Gesamt: {len(entries)} Einträge")

    # Preview
    for desc, abbr in entries[:15]:
        print(f"  {abbr:15s} = {desc}")
    print("  ...")

if __name__ == "__main__":
    main()
